pretrained: false
cfg: ''
data: data/scr.yaml
epochs: 500
batch_size: 16
imgsz: 576
rect: false
resume: null
nosave: false
noval: false
noautoanchor: false
noplots: false
evolve: null
bucket: ''
cache: ram
image_weights: false
device: cuda:0
multi_scale: false
single_cls: false
optimizer: Adam
sync_bn: false
workers: 8
project: runs/train
name: exp
exist_ok: false
quad: false
cos_lr: false
label_smoothing: 0.0
patience: 150
freeze:
- 0
save_period: -1
seed: 0
local_rank: -1
r: 1
space: 1
entity: null
upload_dataset: false
bbox_interval: -1
artifact_alias: latest
save_dir: runs/train/exp
